"""add_user_password

Revision ID: 8fbd8c490a50
Revises: 3c41945c1670
Create Date: 2024-12-14 12:08:00.734474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbd8c490a50'
down_revision: Union[str, None] = '3c41945c1670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_question_technology_id'), 'question_technology', ['id'])
    op.add_column('user', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_constraint(op.f('uq_question_technology_id'), 'question_technology', type_='unique')
    # ### end Alembic commands ###
