"""add_question_technology

Revision ID: 8731a349383d
Revises: 86ce371678be
Create Date: 2024-12-14 11:21:58.855470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8731a349383d'
down_revision: Union[str, None] = '86ce371678be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_assessment', sa.Column('answer_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(op.f('uq_ai_assessment_id'), 'ai_assessment', ['id'])
    op.create_foreign_key(op.f('fk_ai_assessment_answer_id_answer'), 'ai_assessment', 'answer', ['answer_id'], ['id'])
    op.create_unique_constraint(op.f('uq_answer_id'), 'answer', ['id'])
    op.create_unique_constraint(op.f('uq_question_id'), 'question', ['id'])
    op.drop_constraint('fk_question_technology_id_technology', 'question', type_='foreignkey')
    op.drop_constraint('fk_question_sub_technology_id_technology', 'question', type_='foreignkey')
    op.drop_column('question', 'sub_technology_id')
    op.drop_column('question', 'technology_id')
    op.create_unique_constraint(op.f('uq_technology_id'), 'technology', ['id'])
    op.create_unique_constraint(op.f('uq_user_question_id'), 'user_question', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_question_id'), 'user_question', type_='unique')
    op.drop_constraint(op.f('uq_technology_id'), 'technology', type_='unique')
    op.add_column('question', sa.Column('technology_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('sub_technology_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_question_sub_technology_id_technology', 'question', 'technology', ['sub_technology_id'], ['id'])
    op.create_foreign_key('fk_question_technology_id_technology', 'question', 'technology', ['technology_id'], ['id'])
    op.drop_constraint(op.f('uq_question_id'), 'question', type_='unique')
    op.drop_constraint(op.f('uq_answer_id'), 'answer', type_='unique')
    op.drop_constraint(op.f('fk_ai_assessment_answer_id_answer'), 'ai_assessment', type_='foreignkey')
    op.drop_constraint(op.f('uq_ai_assessment_id'), 'ai_assessment', type_='unique')
    op.drop_column('ai_assessment', 'answer_id')
    # ### end Alembic commands ###
