"""add_index_user_tg_id

Revision ID: fa38cea6da7c
Revises: bcaa40f039df
Create Date: 2025-02-19 16:14:42.791803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa38cea6da7c'
down_revision: Union[str, None] = 'bcaa40f039df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ai_assessment', ['id'])
    op.create_unique_constraint(None, 'answer', ['id'])
    op.create_unique_constraint(None, 'error', ['id'])
    op.create_unique_constraint(None, 'question', ['id'])
    op.create_unique_constraint(None, 'question_technology', ['id'])
    op.create_unique_constraint(None, 'technology', ['id'])
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_question', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_question', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_constraint(None, 'technology', type_='unique')
    op.drop_constraint(None, 'question_technology', type_='unique')
    op.drop_constraint(None, 'question', type_='unique')
    op.drop_constraint(None, 'error', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    op.drop_constraint(None, 'ai_assessment', type_='unique')
    # ### end Alembic commands ###
