"""add_index_user_tg_id_unique

Revision ID: b4c3c4227495
Revises: fa38cea6da7c
Create Date: 2025-02-19 16:15:38.624979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c3c4227495'
down_revision: Union[str, None] = 'fa38cea6da7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tg_id', table_name='user')
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.create_index('ix_user_tg_id', 'user', ['tg_id'], unique=False)
    # ### end Alembic commands ###
