"""add_score_to_assessment

Revision ID: 2160de54e874
Revises: b4c3c4227495
Create Date: 2025-03-09 14:04:15.219835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2160de54e874'
down_revision: Union[str, None] = 'b4c3c4227495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_assessment', sa.Column('score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_assessment', 'score')
    # ### end Alembic commands ###
